name: "controldreamernerfstrict-sd21-shading"
tag: "${rmspace:${system.prompt_processor.prompt},_}"
exp_root_dir: "outputs"
seed: 0

# data_type: "random-multiview-camera-datamodule"
data_type: "mvdream-random-multiview-camera-datamodule"
data:
  batch_size: [8,4] # must be dividable by n_view
  n_view: 4
  # 0-4999: 64x64, >=5000: 256x256
  width: [64, 256]
  height: [64, 256]
  resolution_milestones: [10000]
  camera_distance_range: [0.8, 1.0] # relative
  fovy_range: [15, 60]
  elevation_range: [0, 30]
  camera_perturb: 0.
  center_perturb: 0.
  up_perturb: 0.
  n_val_views: 4
  eval_camera_distance: 3.0
  eval_fovy_deg: 40.

system_type: "mvdream-strict-control-system"
system:
  control_renderer_type: "nvdiff-obj-rasterizer"
  control_renderer:
    file_path: ???
    masked_segments: ???
    # Mesh
    # file_path: "/home/codeysun/git/data/PartObjaverse-Tiny/PartObjaverse-Tiny_mesh/00aee5c2fef743d69421bb642d446a5b.glb"
    # file_path: "/home/codeysun/git/PartField/data/partnet/mesh/25256.obj"
    # semantic face predictions
    # masked_segments: "/home/codeysun/git/PartField/exp_results/clustering/partobjtiny/sem_preds/00aee5c2fef743d69421bb642d446a5b/Basket.npy"
    # masked_segments: "/home/codeysun/git/PartField/exp_results/clustering/partnet/sem_preds/25256/Tabletop.npy"

    # old
    # file_path: "/home/codeysun/git/data/PartNet/data_v0/8677/objs"
    # masked_segments: ["original-3.obj"]
    # file_path: "/home/codeysun/git/data/PartNet/data_v0/14102/objs"
    # masked_segments: ["new-0.obj", "new-1.obj"]
    # file_path: "/home/codeysun/git/data/PartNet/data_v0/555/objs"
    # masked_segments: ["new-4.obj", "new-0.obj","new-1.obj","new-2.obj","new-3.obj",]
    default_control: 0
    local_control: True

  refinement: false
  # geometry_convert_from: ???
  geometry_convert_inherit_texture: true
  geometry_type: "implicit-volume"
  geometry:
    radius: 1.0
    normal_type: "analytic"

    density_bias: "blob_magic3d"
    density_activation: softplus
    density_blob_scale: 10.
    density_blob_std: 0.5

    pos_encoding_config:
      otype: HashGrid
      n_levels: 16
      n_features_per_level: 2
      log2_hashmap_size: 19
      base_resolution: 16
      per_level_scale: 1.447269237440378 # max resolution 4096

  material_type: "diffuse-with-point-light-material"
  material:
    ambient_only_steps: 5000
    textureless_prob: 0.5
    ambient_light_color: [1.0, 1.0, 1.0]
    diffuse_light_color: [0.0, 0.0, 0.0]
    soft_shading: true
    albedo_activation: sigmoid

  background_type: "mvdream-neural-environment-map-background"
  background:
    color_activation: sigmoid
    random_aug: true
    share_aug_bg: true

  renderer_type: "nerf-volume-renderer"
  renderer:
    radius: ${system.geometry.radius}
    num_samples_per_ray: 128

  prompt_processor_type: "stable-diffusion-prompt-processor"
  prompt_processor:
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
    prompt: ???
    negative_prompt: "ugly, bad anatomy, blurry, pixelated obscure, unnatural colors, poor lighting, dull, and unclear, cropped, lowres, low quality, artifacts, duplicate, morbid, mutilated, poorly drawn face, deformed, dehydrated, bad proportions"
    front_threshold: 30.
    back_threshold: 30.

  guidance_type: "multiview-control-guidance"
  guidance:
    model_name: './extern/MVDream/mvdream/configs/cldm_v21_mvdream.yaml'
    ckpt_path: './extern/MVDream/mvdream/ckpt/depth_model.ckpt' # path to a pre-downloaded checkpoint file
    guidance_scale: 50.0
    min_step_percent: [0, 0.98, 0.02, 4000]  # (start_iter, start_val, end_val, end_iter)
    max_step_percent: [0, 0.98, 0.50, 4000]
    recon_loss: true
    control_freq: 1
    control_scale: 1.0
    recon_std_rescale: 0.5

  loggers:
    wandb:
      enable: false
      project: 'threestudio'

  # loss:
  #   lambda_sds: 1.
  #   lambda_normal_consistency: 10000.
  #   lambda_laplacian_smoothness: 10000.
  loss:
    lambda_sds: 1.
    lambda_orient: [0, 10., 1000., 5000]
    lambda_sparsity: 0.
    lambda_opaque: 0.
    lambda_z_variance: 0.

  optimizer:
    name: AdamW
    args:
      betas: [0.9, 0.99]
      eps: 1.e-15
    params:
      geometry.encoding:
        lr: 0.01
      geometry.density_network:
        lr: 0.001
      geometry.feature_network:
        lr: 0.001
      background:
        lr: 0.001

trainer:
  max_steps: 5000
  log_every_n_steps: 1
  num_sanity_val_steps: 0
  val_check_interval: 500
  enable_progress_bar: true
  # precision: 32
  precision: 16-mixed

checkpoint:
  save_last: true
  save_top_k: -1
  every_n_train_steps: ${trainer.max_steps}
